/**!
 *
 * Copyright (c) 2026 Apple Inc. Licensed under MIT License.
 */

import { MapKit } from "apple-mapkit/mapkit";
export type * from "apple-mapkit/mapkit";

export interface MapKitLoaderOptions {
  /**
   * Token to initialize MapKit JS.
   * Required, unless you intend to call `mapkit.init()` later.
   */
  token?: string;

  /**
   * One time value for Content Security Policy.
   *
   * See [Implement a Content Security Policy](https://developer.apple.com/documentation/mapkitjs/loading-the-latest-version-of-mapkit-js#Implement-a-Content-Security-Policy) for more information.
   */
  nonce?: string;

  /**
   * The language to set for MapKit JS. A language ID is a language designator followed by an optional
   * region or script designator.
   */
  language?: string;

  /**
   *  List of libraries to load at initialization.
   *
   *  See [Select MapKit JS libraries](https://developer.apple.com/documentation/mapkitjs/loading-the-latest-version-of-mapkit-js#Select-MapKit-JS-libraries) for list of available libraries.
   */
  libraries?: string[];

  /**
   * Desired MapKit JS version.
   */
  version?: string;

  /**
   * Additional data attributes to set. Keys should be in snake case without the `data-` prefix.
   */
  data?: Record<string, string>;
}

const CDN_URL = `https://cdn.apple-mapkit.com/mk/%version%/mapkit.core.js`;

const CALLBACK_NAME = "initMapKitLoaderV2";

/**
 * Loads MapKit JS asynchronously.
 * Loading is triggered when the function is called.
 *
 * To optimize the loading, you should call this function as early as possible,
 * or inject the script tag generated by {@link renderToHTMLString} in HTML.
 *
 * @returns The MapKit JS namespace object.
 */
export async function load(options: MapKitLoaderOptions): Promise<MapKit> {
  const { version = "6", token, nonce, language, libraries, data } = options;
  const url = CDN_URL.replace("%version%", version);
  if (version.startsWith("5")) {
    throw new Error(
      "[MapKit Loader] Use Loader version 0 for loading MapKit JS 5.",
    );
  }

  let scriptElement = document.head.querySelector(
    `[data-callback="${CALLBACK_NAME}"]`,
  ) as HTMLScriptElement | null;

  if (!scriptElement) {
    // Construct a new script tag.
    scriptElement = document.createElement("script");
    scriptElement.async = true;
    scriptElement.crossOrigin = "";
    scriptElement.src = url;
    scriptElement.dataset.callback = CALLBACK_NAME;
    if (token) {
      scriptElement.dataset.token = token;
    }

    if (nonce) {
      scriptElement.nonce = nonce;
    }

    if (language) {
      scriptElement.dataset.language = language;
    }

    if (libraries) {
      scriptElement.dataset.libraries = libraries.join(",");
    }

    if (data) {
      for (const [key, value] of Object.entries(data)) {
        scriptElement.setAttribute(`data-${key}`, value);
      }
    }
    document.head.appendChild(scriptElement);
  }

  // Wait for availability of `window.mapkit` from `mapkit.core.js`.
  const mapkit =
    window.mapkit ??
    (await new Promise<MapKit>((resolve, reject) => {
      const onLoad = () => {
        scriptElement.removeEventListener("load", onLoad);
        scriptElement.removeEventListener("error", onError);
        resolve(window.mapkit);
      };
      const onError = () => {
        scriptElement.removeEventListener("load", onLoad);
        scriptElement.removeEventListener("error", onError);
        reject(new Error("[MapKit Loader] mapkit.core.js failed to load."));
      };
      scriptElement.addEventListener("load", onLoad);
      scriptElement.addEventListener("error", onError);
    }));

  // Call mapkit.load() again to ensure libraries are loaded or getting a rejected Promise with library loading error.
  if (!mapkit?.load) {
    throw new Error(
      "[MapKit Loader] mapkit.core.js were loaded but `mapkit` object is not available.",
    );
  }

  return libraries ? mapkit.load(libraries) : mapkit;
}

function escapeHTMLAttributes(str: string) {
  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");
}

/**
 * Generate HTML attributes for a `<script>` tag
 * to start loading MapKit JS as soon as HTML is parsed.
 *
 * This function is useful for integrating the loader with
 * the virtual DOM framework when employing server-side rendering.
 * The attributes are not escaped and must be escaped by
 * the virtual DOM framework when rendering to HTML string.
 *
 * `load()` will then be able to pick up the loaded `mapkit` object
 * in your application. You must ensure the `<script>` tag is present
 * in the DOM before `load()` is invoked.
 *
 * For example, you can use these attributes as props for a React browser [`<script>` component](https://react.dev/reference/react-dom/components/script),
 * and generate a HTML `<script>` tag in `<head>` with [React Helmet](https://www.npmjs.com/package/react-helmet):
 *
 * ```javascript
 * import React from "react";
 * import { Helmet } from "react-helmet";
 * import { renderHTMLAttributes } from "@apple/mapkit-loader";
 *
 * export function App(props) {
 *   return (
 *     <div className='App'>
 *       <Helmet>
 *         <title>My App</title>
 *         <script {...renderHTMLAttributes({ token: "TOKEN" })} />
 *       </Helmet>
 *       <h1>Hello React.</h1>
 *     </div>
 *   );
 * }
 * ```
 *
 * The example above only speeds up MapKit JS load when server-side rendering
 * is integrated.
 *
 * @returns HTML attributes
 */
export function renderHTMLAttributes({
  version = "6",
  nonce,
  token,
  language,
  libraries,
  data,
}: MapKitLoaderOptions): Record<string, string | boolean> {
  if (version.startsWith("5")) {
    throw new Error(
      "[MapKit Loader] Use Loader version 0 for loading MapKit JS 5.",
    );
  }
  const url = CDN_URL.replace("%version%", version);
  const attributes: Record<string, string | boolean> = {
    src: url,
    crossOrigin: "",
    async: true,
    "data-callback": CALLBACK_NAME,
  };

  if (nonce) {
    attributes["nonce"] = nonce;
  }

  if (token) {
    attributes["data-token"] = token;
  }

  if (language) {
    attributes["data-language"] = language;
  }

  if (libraries) {
    attributes["data-libraries"] = libraries.join(",");
  }

  if (data) {
    for (const [key, value] of Object.entries(data)) {
      attributes[`data-${key}`] = value;
    }
  }

  return attributes;
}

/**
 * Generate a HTML string containing one `<script>` tag,
 * start loading MapKit JS as soon as HTML is parsed.
 *
 * `load()` will be able to pick up the loaded `mapkit` object
 * in your application.
 *
 * For example, this is how you can insert the HTML string into Pug template:
 *
 * ```pug
 * head
 *   title My App
 *   != mapkitScript
 * ```
 *
 * and in JavaScript:
 *
 * ```js
 * import pug from "pug";
 *
 * pug.renderFile(
 *   "template.pug",
 *   { mapkitScript: renderToHTMLString({ token: "TOKEN" }) }
 * );
 * ```
 *
 * @returns HTML string
 */
export function renderToHTMLString(options: MapKitLoaderOptions): string {
  const attributes = renderHTMLAttributes(options);

  return `<script ${Object.entries(attributes)
    .map(([key, value]) =>
      value && typeof value === "string"
        ? `${escapeHTMLAttributes(key)}="${escapeHTMLAttributes(value)}"`
        : escapeHTMLAttributes(key),
    )
    .join(" ")}></script>`;
}
